package footprint

func Sites() []Site {
	return []Site{
		{Name: "GitHub", URLMain: "https://github.com/", ProbeURL: "https://github.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "GitLab", URLMain: "https://gitlab.com/", ProbeURL: "https://gitlab.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Twitter / X", URLMain: "https://x.com/", ProbeURL: "https://x.com/{username}", Method: "GET", ErrorType: "message", ErrorValues: []string{"account doesn't exist", "account doesn’t exist", "this account doesn"}},
		{Name: "Reddit", URLMain: "https://reddit.com/", ProbeURL: "https://www.reddit.com/user/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Instagram", URLMain: "https://instagram.com/", ProbeURL: "https://www.instagram.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "TikTok", URLMain: "https://tiktok.com/", ProbeURL: "https://www.tiktok.com/@{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Twitch", URLMain: "https://twitch.tv/", ProbeURL: "https://www.twitch.tv/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "LinkedIn", URLMain: "https://linkedin.com/", ProbeURL: "https://www.linkedin.com/in/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Medium", URLMain: "https://medium.com/", ProbeURL: "https://medium.com/@{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Telegram", URLMain: "https://t.me/", ProbeURL: "https://t.me/{username}", Method: "GET", ErrorType: "message", ErrorValues: []string{"if you have telegram, you can contact"}},
		{Name: "Pinterest", URLMain: "https://pinterest.com/", ProbeURL: "https://www.pinterest.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "SoundCloud", URLMain: "https://soundcloud.com/", ProbeURL: "https://soundcloud.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Steam", URLMain: "https://steamcommunity.com/", ProbeURL: "https://steamcommunity.com/id/{username}", Method: "GET", ErrorType: "message", ErrorValues: []string{"the specified profile could not be found"}},
		{Name: "DeviantArt", URLMain: "https://deviantart.com/", ProbeURL: "https://www.deviantart.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Tumblr", URLMain: "https://tumblr.com/", ProbeURL: "https://{username}.tumblr.com", Method: "GET", ErrorType: "status_code"},
		{Name: "Flickr", URLMain: "https://flickr.com/", ProbeURL: "https://www.flickr.com/people/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Dribbble", URLMain: "https://dribbble.com/", ProbeURL: "https://dribbble.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Behance", URLMain: "https://behance.net/", ProbeURL: "https://www.behance.net/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Vimeo", URLMain: "https://vimeo.com/", ProbeURL: "https://vimeo.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Keybase", URLMain: "https://keybase.io/", ProbeURL: "https://keybase.io/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Gravatar", URLMain: "https://gravatar.com/", ProbeURL: "https://gravatar.com/{username}", Method: "GET", ErrorType: "response_url"},
		{Name: "Docker Hub", URLMain: "https://hub.docker.com/", ProbeURL: "https://hub.docker.com/u/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "npm", URLMain: "https://npmjs.com/", ProbeURL: "https://www.npmjs.com/~{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "PyPI", URLMain: "https://pypi.org/", ProbeURL: "https://pypi.org/user/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "HackerNews", URLMain: "https://news.ycombinator.com/", ProbeURL: "https://news.ycombinator.com/user?id={username}", Method: "GET", ErrorType: "message", ErrorValues: []string{"no such user"}},
		{Name: "StackOverflow", URLMain: "https://stackoverflow.com/", ProbeURL: "https://stackoverflow.com/users/_/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Bitbucket", URLMain: "https://bitbucket.org/", ProbeURL: "https://bitbucket.org/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Codeberg", URLMain: "https://codeberg.org/", ProbeURL: "https://codeberg.org/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "SourceForge", URLMain: "https://sourceforge.net/", ProbeURL: "https://sourceforge.net/u/{username}/", Method: "GET", ErrorType: "status_code"},
		{Name: "TryHackMe", URLMain: "https://tryhackme.com/", ProbeURL: "https://tryhackme.com/p/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "HackTheBox", URLMain: "https://hackthebox.com/", ProbeURL: "https://app.hackthebox.com/profile/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "LeetCode", URLMain: "https://leetcode.com/", ProbeURL: "https://leetcode.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "HackerRank", URLMain: "https://hackerrank.com/", ProbeURL: "https://www.hackerrank.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Codeforces", URLMain: "https://codeforces.com/", ProbeURL: "https://codeforces.com/profile/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Spotify", URLMain: "https://open.spotify.com/", ProbeURL: "https://open.spotify.com/user/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Bandcamp", URLMain: "https://bandcamp.com/", ProbeURL: "https://{username}.bandcamp.com", Method: "GET", ErrorType: "status_code"},
		{Name: "Goodreads", URLMain: "https://goodreads.com/", ProbeURL: "https://www.goodreads.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Mastodon (mastodon.social)", URLMain: "https://mastodon.social/", ProbeURL: "https://mastodon.social/@{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Lobsters", URLMain: "https://lobste.rs/", ProbeURL: "https://lobste.rs/u/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Giphy", URLMain: "https://giphy.com/", ProbeURL: "https://giphy.com/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Pastebin", URLMain: "https://pastebin.com/", ProbeURL: "https://pastebin.com/u/{username}", Method: "GET", ErrorType: "status_code"},
		{Name: "Archive.org", URLMain: "https://archive.org/", ProbeURL: "https://archive.org/details/@{username}", Method: "GET", ErrorType: "status_code"},
	}
}
